---
# Tasks to setup network

- name: Fetch node files
  git:
    repo: "https://{{ network_launch_repository }}.git"
    dest: "/data/launch"
    recursive: false
    version: "{{ network_launch_branch }}"

- name: Setup node directory
  command: cp -rf /data/launch/{{ network_version }}/{{ node_type }} /data/node

- name: Setup Heidmall
  command: "chdir=/data/node/heimdall {{ item }}"
  with_items:
    - bash setup.sh
  tags:
    - heimdall

- name: Setup Bor
  command: "chdir=/data/node/bor {{ item }}"
  with_items:
    - bash setup.sh
  tags:
    - bor

- name: Generate service files
  command: "chdir=/data/launch/{{ network_version }} {{ item }}"
  with_items:
    - bash service.sh
